version: '3'
services:
  backend:
    build: ./backend
    ports:
        - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
      - MONGO_CONNECT=mongodb://mongodb:27017
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
        - "8005:8005"
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
  mongodb:
    image: "mongo"
    volumes:
      - ./data:/data/db
    ports:
     - "27017:27017"