version: '3'
services:
  backend:
    build: ./backend
    ports:
        - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
      - VIRTUAL_HOST=mdpubapi.costa365.site
      - PORT=8005
      - MONGO_CONNECT=mongodb://mongodb:27017
    depends_on:
      - mongodb
    restart: always
    networks:
      - nginx-proxy
      - app-net
  frontend:
    build: ./frontend
    ports:
        - "8005:8005"
    volumes:
      - ./frontend:/frontend
    environment:
      - VIRTUAL_HOST=mdpub.costa365.site
      - PORT=8005
      - BACKEND=https://mdpubapi.costa365.site
    depends_on:
      - backend
    restart: always
    networks:
      - nginx-proxy
      - app-net
  mongodb:
    image: "mongo:4.4.6"
    volumes:
      - ./data:/data/db
    ports:
     - "27017:27017"
    restart: always
    networks:
      - app-net
networks:
  nginx-proxy:
    external: true
  app-net:
    internal: true
