version: '3'
services:
  backend:
    build: ./backend
    ports:
        - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
      - MONGO_CONNECT=${MONGO_CONNECT}
  frontend:
    build: ./frontend
    ports:
        - "8005:8005"
    volumes:
      - ./frontend:/frontend
    environment:
      - BACKEND=http://127.0.0.1:8000
    depends_on:
      - backend
